Repository htw-imi-showtime/showtime-website, pull requests merged in 2025-07, with the labels that each got.

#440 M5 - Javacademy
  content/ss25/master/m5-fun-with-programming/_index.md
  content/ss25/master/m5-fun-with-programming/features.md
  content/ss25/master/m5-fun-with-programming/logo.svg
  content/ss25/master/m5-fun-with-programming/process.md
  content/ss25/master/m5-fun-with-programming/screenshots/homepage-screenshot.png
  content/ss25/master/m5-fun-with-programming/screenshots/lecture-content.png
  content/ss25/master/m5-fun-with-programming/team/gerrit.png
  content/ss25/master/m5-fun-with-programming/team/julius.png
  content/ss25/master/m5-fun-with-programming/team/max.png
  content/ss25/master/m5-fun-with-programming/team/uyen.png
  content/ss25/master/m5-fun-with-programming/tools.md
  content/ss25/master/m5-fun-with-programming/tools/docker.png
  content/ss25/master/m5-fun-with-programming/tools/figma.png
  content/ss25/master/m5-fun-with-programming/tools/gitlab.png
  content/ss25/master/m5-fun-with-programming/tools/htw.png
  content/ss25/master/m5-fun-with-programming/tools/javascript.png
  content/ss25/master/m5-fun-with-programming/tools/miro.png
  content/ss25/master/m5-fun-with-programming/tools/my-sql.png
  content/ss25/master/m5-fun-with-programming/tools/nuxt.png
  content/ss25/master/m5-fun-with-programming/tools/pinia.png
  content/ss25/master/m5-fun-with-programming/tools/strapi.png
  content/ss25/master/m5-fun-with-programming/tools/tailwind.png
  content/ss25/master/m5-fun-with-programming/tools/typescript.png
  content/ss25/master/m5-fun-with-programming/tools/vite.png
Labels: ok_to_merge

#453 M2 M3 split
  .github/workflows/check-project-update.yml
  bin/check-project-update-pr/check-file-names.sh
  content/ss25/master/m2-genesis/_index.md
  content/ss25/master/m2-genesis/freddie_img.jpg
  content/ss25/master/m2-genesis/genesis-et-civitas.content
  content/ss25/master/m2-genesis/genesis-et-civitas.md
  content/ss25/master/m2-genesis/genesis1_img.jpg
  content/ss25/master/m2-genesis/genesis2_img.jpg
  content/ss25/master/m2-genesis/marvin_img.jpg
  content/ss25/master/m2-genesis/oliver_img.jpg
  content/ss25/master/m2-genesis/toni_img.jpg
  content/ss25/master/m2-m3-genesisetcivitas/trigger-build.md
  content/ss25/master/m3-civitas/_index.md
  content/ss25/master/m3-civitas/civ_img.jpg
  content/ss25/master/m3-civitas/civ_ui_img.jpg
  content/ss25/master/m3-civitas/dj_img.jpg
  content/ss25/master/m3-civitas/genesis-et-civitas.md
  content/ss25/master/m3-civitas/krist_img.jpg
  content/ss25/master/m3-civitas/laura_img.jpg
  content/ss25/master/m3-civitas/liz_img.jpg
  themes/showtime-theme-2024/layouts/_default/project.html
  themes/showtime-theme-2024/layouts/shortcodes/include-file.html
Labels: Needs Changes

#450 M1 - First release train
  content/ss25/master/m1-directors-cut-360/_index.md
  content/ss25/master/m1-directors-cut-360/dc_gui.jpg
  content/ss25/master/m1-directors-cut-360/dcv_logo.png
  content/ss25/master/m1-directors-cut-360/details.md
  content/ss25/master/m1-directors-cut-360/team_anton.jpg
  content/ss25/master/m1-directors-cut-360/team_sebastian.jpg
  content/ss25/master/m1-directors-cut-360/tools.md
Labels: reduce file sizes
